"""Harvard AIS Bedrock LLM provider implementation with vision support."""

import os
import json
import threading
import time
import logging
import requests
from typing import Optional
from pathlib import Path
from .base import LLMProvider
from ..core.exceptions import ProcessingError

logger = logging.getLogger(__name__)

# HTTP status codes worth retrying
_RETRYABLE_STATUS_CODES = {429, 500, 502, 503, 504}

# Models with low rate limits — enforce minimum delay between requests (seconds)
_RATE_LIMITED_MODELS = {
    'us.mistral.pixtral-large-2502-v1:0': 5.0,
}

# Models that use V1 legacy endpoint (us.* cross-region + old non-prefixed models)
_V1_LEGACY_MODELS = {
    'anthropic.claude-3-5-sonnet-20241022-v2:0',
    'anthropic.claude-3-5-haiku-20241022-v1:0',
    'anthropic.claude-3-opus-20240229-v1:0',
    'meta.llama3-3-70b-instruct-v1:0',
    'meta.llama3-1-405b-instruct-v1:0',
}


class HarvardBedrockProvider(LLMProvider):
    """Harvard AIS Bedrock LLM provider using REST API with vision support."""

    # Class-level rate limiter shared across instances
    _rate_locks: dict = {}
    _last_request_time: dict = {}
    _RATE_LIMIT_LOCK = threading.Lock()
    
    # API base URLs
    API_BASE_URLS = {
        'v1': 'https://go.apis.huit.harvard.edu/ais-bedrock-llm/v1',
        'v2': 'https://go.apis.huit.harvard.edu/ais-bedrock-llm/v2'
    }
    
    def __init__(self, model_name: str, api_key: Optional[str] = None,
                 api_version: str = 'v2', temperature: float = 0.0,
                 max_tokens: int = 512, timeout: int = 60,
                 max_retries: int = 3, retry_base_delay: float = 5.0):
        """
        Initialize Harvard Bedrock provider.

        Args:
            model_name: Bedrock model name (e.g., 'us.anthropic.claude-opus-4-5-20251101-v1:0')
            api_key: API key (defaults to environment variable HARVARD_API_KEY)
            api_version: API version ('v1' or 'v2', defaults to 'v2')
            temperature: Sampling temperature
            max_tokens: Maximum tokens to generate
            timeout: Request timeout in seconds
            max_retries: Maximum number of retries on transient errors (504, 429, etc.)
            retry_base_delay: Base delay in seconds between retries (exponential backoff)
        """
        super().__init__(model_name)
        self.api_key = api_key or os.getenv('HARVARD_API_KEY')
        self.api_version = api_version
        self.temperature = temperature
        self.max_tokens = max_tokens
        self.timeout = timeout
        self.max_retries = max_retries
        self.retry_base_delay = retry_base_delay
        
        # Validate API version
        if self.api_version not in self.API_BASE_URLS:
            raise ProcessingError(f"Invalid API version: {self.api_version}. Must be 'v1' or 'v2'")
        
        self.base_url = self.API_BASE_URLS[self.api_version]
    
    def query(self, prompt: str, system_prompt: str = None, image_path: Optional[str] = None,
              image_paths: Optional[list] = None) -> tuple:
        """
        Query Harvard Bedrock model with a prompt and optional image(s).
        
        Args:
            prompt: Input prompt
            system_prompt: Optional system prompt to set context
            image_path: Optional path to single image file
            image_paths: Optional list of paths to image files
            
        Returns:
            Tuple of (response_text, token_metadata) where token_metadata contains:
            {
                'input_tokens': int,   # Tokens sent to LLM (text + images)
                'output_tokens': int   # Tokens generated by LLM
            }
            
        Raises:
            ProcessingError: If query fails
        """
        if not self.validate_prompt(prompt):
            raise ProcessingError("Invalid prompt provided")
        
        if not self.api_key:
            raise ProcessingError("Harvard API key not configured")
        
        try:
            # Determine which images to use
            images_to_process = []
            if image_paths:
                images_to_process = [img for img in image_paths if Path(img).exists()]
            elif image_path and Path(image_path).exists():
                images_to_process = [image_path]
            
            # Determine which API format to use based on model
            # 1. us.anthropic.* → V2 Anthropic Messages API
            # 2. us.meta.*, us.mistral.* + legacy non-prefixed → V1 InvokeModel
            # 3. amazon.nova-* → V2 invoke with Nova-specific format
            # 4. Everything else (deepseek, qwen, gemma, etc.) → V2 invoke with messages format
            if self.model_name.startswith('us.anthropic.'):
                payload = self._build_v2_payload(prompt, system_prompt, images_to_process)
                url = f"{self.base_url}/model/{self.model_name}/invoke"
            elif self.model_name.startswith('us.') or self.model_name in _V1_LEGACY_MODELS:
                payload = self._build_v1_payload(prompt, system_prompt, images_to_process)
                url = self.API_BASE_URLS['v1']
            elif self.model_name.startswith('amazon.nova'):
                payload = self._build_nova_payload(prompt, system_prompt, images_to_process)
                url = f"{self.API_BASE_URLS['v2']}/model/{self.model_name}/invoke"
            else:
                payload = self._build_messages_payload(prompt, system_prompt, images_to_process)
                url = f"{self.API_BASE_URLS['v2']}/model/{self.model_name}/invoke"
            
            # Rate limit for throttled models (e.g. Pixtral)
            self._wait_for_rate_limit()

            # Make API request with retry
            headers = {
                'Content-Type': 'application/json',
                'x-api-key': self.api_key
            }

            last_error = None
            for attempt in range(1, self.max_retries + 1):
                try:
                    response = requests.post(
                        url,
                        headers=headers,
                        json=payload,
                        timeout=self.timeout
                    )

                    if response.status_code == 200:
                        # Success — parse and return
                        result = response.json()
                        response_text = self._extract_response_text(result)
                        token_metadata = self._extract_token_usage(result)

                        # Clean up Pixtral responses that may have unwanted text before JSON
                        if 'mistral' in self.model_name.lower() and '{{' in response_text:
                            json_start = response_text.find('{{')
                            if json_start > 0:
                                response_text = response_text[json_start:]

                        return response_text, token_metadata

                    # Retryable server error
                    if response.status_code in _RETRYABLE_STATUS_CODES:
                        try:
                            error_data = response.json()
                            detail = error_data.get('message', error_data)
                        except Exception:
                            detail = response.text
                        last_error = f"API request failed with status {response.status_code}: {detail}"
                        if attempt < self.max_retries:
                            delay = self.retry_base_delay * (2 ** (attempt - 1))
                            logger.warning("Attempt %d/%d failed (%d), retrying in %.0fs…",
                                           attempt, self.max_retries, response.status_code, delay)
                            time.sleep(delay)
                            continue

                    # Non-retryable HTTP error — fail immediately
                    error_msg = f"API request failed with status {response.status_code}"
                    try:
                        error_data = response.json()
                        error_msg += f": {error_data.get('message', error_data)}"
                    except Exception:
                        error_msg += f": {response.text}"
                    raise ProcessingError(error_msg)

                except requests.exceptions.Timeout:
                    last_error = f"Request timed out after {self.timeout} seconds"
                    if attempt < self.max_retries:
                        delay = self.retry_base_delay * (2 ** (attempt - 1))
                        logger.warning("Attempt %d/%d timed out, retrying in %.0fs…",
                                       attempt, self.max_retries, delay)
                        time.sleep(delay)
                        continue

                except requests.exceptions.RequestException as e:
                    last_error = f"Harvard Bedrock API error: {str(e)}"
                    if attempt < self.max_retries:
                        delay = self.retry_base_delay * (2 ** (attempt - 1))
                        logger.warning("Attempt %d/%d network error, retrying in %.0fs…",
                                       attempt, self.max_retries, delay)
                        time.sleep(delay)
                        continue

            # All retries exhausted
            raise ProcessingError(f"Failed after {self.max_retries} attempts: {last_error}")

        except ProcessingError:
            raise
        except Exception as e:
            raise ProcessingError(f"Unexpected error: {str(e)}")
    
    def _wait_for_rate_limit(self):
        """Enforce per-model rate limiting for throttled models."""
        min_interval = _RATE_LIMITED_MODELS.get(self.model_name)
        if min_interval is None:
            return

        with self._RATE_LIMIT_LOCK:
            if self.model_name not in self._rate_locks:
                self._rate_locks[self.model_name] = threading.Lock()
                self._last_request_time[self.model_name] = 0.0

        with self._rate_locks[self.model_name]:
            now = time.monotonic()
            elapsed = now - self._last_request_time[self.model_name]
            if elapsed < min_interval:
                time.sleep(min_interval - elapsed)
            self._last_request_time[self.model_name] = time.monotonic()

    def _build_v2_payload(self, prompt: str, system_prompt: Optional[str],
                          images: list) -> dict:
        """Build payload for API v2 (Anthropic Messages API format)."""
        # Build message content
        content = []
        
        # Add images first if present (for vision models)
        if images:
            for img_path in images:
                img_ext = Path(img_path).suffix.lower()
                if img_ext in ['.jpg', '.jpeg']:
                    media_type = 'image/jpeg'
                elif img_ext == '.png':
                    media_type = 'image/png'
                elif img_ext == '.gif':
                    media_type = 'image/gif'
                elif img_ext == '.webp':
                    media_type = 'image/webp'
                else:
                    media_type = 'image/png'  # Default
                
                content.append({
                    "type": "image",
                    "source": {
                        "type": "base64",
                        "media_type": media_type,
                        "data": self._encode_image(img_path)
                    }
                })
        
        # Add text prompt
        content.append({
            "type": "text",
            "text": prompt
        })
        
        # Build messages array
        messages = [{
            "role": "user",
            "content": content
        }]
        
        # Build payload (Anthropic Messages API format for v2)
        payload = {
            "anthropic_version": "bedrock-2023-05-31",
            "messages": messages,
            "max_tokens": self.max_tokens
        }
        
        # Add temperature if not default (some models are sensitive)
        if self.temperature != 1.0:
            payload["temperature"] = self.temperature
        
        # Add system prompt if provided
        if system_prompt:
            payload["system"] = system_prompt
        
        return payload
    
    def _build_v1_payload(self, prompt: str, system_prompt: Optional[str],
                          images: list) -> dict:
        """Build payload for API v1 (InvokeModel format for Mistral/Llama)."""
        # Combine system prompt with user prompt if provided
        full_prompt = prompt
        if system_prompt:
            full_prompt = f"{system_prompt}\n\n{prompt}"
        
        # V1 uses a simpler body format
        body = {
            "prompt": full_prompt,
            "temperature": self.temperature,
            "top_p": 0.9
        }
        
        # Add max_tokens parameter based on model type
        if 'anthropic' in self.model_name.lower():
            body["max_tokens"] = self.max_tokens
        elif 'mistral' in self.model_name.lower():
            body["max_tokens"] = self.max_tokens
        else:
            # For Llama models
            body["max_gen_len"] = self.max_tokens
        
        # Note: v1 API format doesn't support images in the same way as v2
        # For vision models like Pixtral, images would need special handling
        if images:
            # For Pixtral and other vision models, we might need to encode images
            # This is a placeholder - actual implementation depends on model support
            pass
        
        payload = {
            "modelId": self.model_name,
            "contentType": "application/json",
            "accept": "application/json",
            "body": body
        }
        
        return payload
    
    def _build_messages_payload(self, prompt: str, system_prompt: Optional[str],
                                images: list) -> dict:
        """Build payload using OpenAI-compatible messages format for V2 invoke
        (DeepSeek, Qwen, Gemma, Mistral, Moonshot, NVIDIA, etc.)."""
        messages = []

        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})

        # Build user message content
        if images:
            content = []
            for img_path in images:
                img_ext = Path(img_path).suffix.lower()
                if img_ext in ['.jpg', '.jpeg']:
                    media_type = 'image/jpeg'
                elif img_ext == '.png':
                    media_type = 'image/png'
                elif img_ext == '.gif':
                    media_type = 'image/gif'
                elif img_ext == '.webp':
                    media_type = 'image/webp'
                else:
                    media_type = 'image/png'
                content.append({
                    "type": "image_url",
                    "image_url": {
                        "url": f"data:{media_type};base64,{self._encode_image(img_path)}"
                    }
                })
            content.append({"type": "text", "text": prompt})
            messages.append({"role": "user", "content": content})
        else:
            messages.append({"role": "user", "content": prompt})

        payload = {
            "messages": messages,
            "max_tokens": self.max_tokens,
            "temperature": self.temperature,
        }
        return payload

    def _build_nova_payload(self, prompt: str, system_prompt: Optional[str],
                            images: list) -> dict:
        """Build payload for Amazon Nova models (Bedrock InvokeModel format)."""
        content = []

        if images:
            for img_path in images:
                img_ext = Path(img_path).suffix.lower().lstrip('.')
                if img_ext in ('jpg', 'jpeg'):
                    fmt = 'jpeg'
                elif img_ext in ('png', 'gif', 'webp'):
                    fmt = img_ext
                else:
                    fmt = 'png'
                content.append({
                    "image": {
                        "format": fmt,
                        "source": {"bytes": self._encode_image(img_path)}
                    }
                })

        content.append({"text": prompt})

        payload = {
            "messages": [{"role": "user", "content": content}],
            "inferenceConfig": {
                "max_new_tokens": self.max_tokens,
                "temperature": self.temperature,
            }
        }

        if system_prompt:
            payload["system"] = [{"text": system_prompt}]

        return payload

    def _extract_response_text(self, response: dict) -> str:
        """Extract text from API response."""
        try:
            # Amazon Nova format - output.message.content
            if 'output' in response and isinstance(response['output'], dict):
                msg = response['output'].get('message', {})
                nova_content = msg.get('content', [])
                if isinstance(nova_content, list):
                    for item in nova_content:
                        if isinstance(item, dict) and 'text' in item:
                            return item['text'].strip()

            # OpenAI-like format (Mistral/Pixtral) - choices array
            if 'choices' in response and isinstance(response['choices'], list) and len(response['choices']) > 0:
                choice = response['choices'][0]
                if 'message' in choice and 'content' in choice['message']:
                    return choice['message']['content'].strip()
            
            # v2 format (Anthropic Messages API) - direct content array
            if 'content' in response:
                content = response['content']
                if isinstance(content, list) and len(content) > 0:
                    for item in content:
                        if isinstance(item, dict) and item.get('type') == 'text':
                            return item.get('text', '').strip()
                    # Fallback to first item if no text type found
                    if isinstance(content[0], dict) and 'text' in content[0]:
                        return content[0]['text'].strip()
                    return str(content[0]).strip()
                elif isinstance(content, str):
                    return content.strip()
            
            # v1 format - response is in 'body' field or directly
            if 'body' in response:
                body = response['body']
                # If body is a string, it might be JSON
                if isinstance(body, str):
                    import json
                    try:
                        body = json.loads(body)
                    except:
                        return body.strip()
                
                # Extract from common response formats
                if isinstance(body, dict):
                    # Anthropic format
                    if 'completion' in body:
                        return body['completion'].strip()
                    # Llama format
                    if 'generation' in body:
                        return body['generation'].strip()
                    # Generic text field
                    if 'text' in body:
                        return body['text'].strip()
                    # Content array
                    if 'content' in body:
                        content = body['content']
                        if isinstance(content, list) and len(content) > 0:
                            if isinstance(content[0], dict) and 'text' in content[0]:
                                return content[0]['text'].strip()
            
            # Fallback: try common text fields
            for field in ['text', 'completion', 'generation', 'response']:
                if field in response:
                    return str(response[field]).strip()
            
            raise ProcessingError(f"Could not extract text from response: {response}")
        except Exception as e:
            raise ProcessingError(f"Error parsing response: {str(e)}")
    
    def _extract_token_usage(self, response: dict) -> dict:
        """
        Extract token usage from API response.
        
        Returns:
            Dictionary with 'input_tokens' and 'output_tokens' keys.
            input_tokens = tokens sent to LLM (text + system prompt + images)
            output_tokens = tokens generated by LLM
            
        Example response structure (V2 - Anthropic):
            {
                "content": [...],
                "usage": {
                    "input_tokens": 156,
                    "output_tokens": 89
                },
                "stop_reason": "end_turn"
            }
            
        Example response structure (V1 - Mistral/Llama):
            {
                "body": {
                    "completion": "...",
                    "usage": {
                        "prompt_tokens": 156,
                        "completion_tokens": 89,
                        "total_tokens": 245
                    }
                }
            }
            
        Example OpenAI-like format (Pixtral):
            {
                "id": "...",
                "object": "text_completion",
                "created": 1234567890,
                "model": "pixtral-large-2502",
                "choices": [
                    {
                        "index": 0,
                        "message": {"content": "..."},
                        "finish_reason": "stop"
                    }
                ],
                "usage": {
                    "prompt_tokens": 156,
                    "completion_tokens": 89,
                    "total_tokens": 245
                }
            }
        """
        token_metadata = {
            'input_tokens': 0,
            'output_tokens': 0
        }
        
        try:
            # Strategy 1: Check for usage at top level (V2 Anthropic or OpenAI-like Pixtral)
            if 'usage' in response:
                usage = response['usage']
                if isinstance(usage, dict):
                    # Try Anthropic format first
                    input_toks = usage.get('input_tokens', 0)
                    output_toks = usage.get('output_tokens', 0)

                    # Fall back to OpenAI/Mistral format if Anthropic format returns 0
                    if input_toks == 0:
                        input_toks = usage.get('prompt_tokens', 0)
                    if output_toks == 0:
                        output_toks = usage.get('completion_tokens', 0)

                    # Fall back to Amazon Nova format
                    if input_toks == 0:
                        input_toks = usage.get('inputTokens', 0)
                    if output_toks == 0:
                        output_toks = usage.get('outputTokens', 0)
                    
                    if input_toks > 0 or output_toks > 0:
                        token_metadata['input_tokens'] = input_toks
                        token_metadata['output_tokens'] = output_toks
                        return token_metadata
            
            # Strategy 2: Check for usage nested in body field (V1 format)
            if 'body' in response:
                body = response['body']
                # If body is a string, parse it as JSON
                if isinstance(body, str):
                    try:
                        body = json.loads(body)
                    except:
                        pass
                
                # Extract usage from body dict
                if isinstance(body, dict):
                    # Check for usage in body
                    if 'usage' in body:
                        usage = body['usage']
                        if isinstance(usage, dict):
                            input_toks = usage.get('prompt_tokens', 0) or usage.get('input_tokens', 0)
                            output_toks = usage.get('completion_tokens', 0) or usage.get('output_tokens', 0)
                            if input_toks > 0 or output_toks > 0:
                                token_metadata['input_tokens'] = input_toks
                                token_metadata['output_tokens'] = output_toks
                                return token_metadata
            
            # Strategy 3: Check for usage in choices array (some OpenAI-like formats)
            if 'choices' in response and isinstance(response['choices'], list):
                for choice in response['choices']:
                    if isinstance(choice, dict) and 'usage' in choice:
                        usage = choice['usage']
                        if isinstance(usage, dict):
                            input_toks = usage.get('prompt_tokens', 0) or usage.get('input_tokens', 0)
                            output_toks = usage.get('completion_tokens', 0) or usage.get('output_tokens', 0)
                            if input_toks > 0 or output_toks > 0:
                                token_metadata['input_tokens'] = input_toks
                                token_metadata['output_tokens'] = output_toks
                                return token_metadata
            
        except Exception as e:
            # If extraction fails, log and return zeros
            print(f"Warning: Could not extract token usage from response: {e}")
        
        return token_metadata
    
    def _encode_image(self, image_path: str) -> str:
        """Encode image to base64 string."""
        import base64
        with open(image_path, "rb") as image_file:
            return base64.b64encode(image_file.read()).decode('utf-8')
    
    def get_model_name(self) -> str:
        """Get the full model name with provider prefix."""
        return f"harvard/{self.model_name}"
    
    def is_available(self) -> bool:
        """Check if Harvard Bedrock provider is available."""
        return bool(self.api_key)
    
    def get_provider_info(self) -> dict:
        """Get detailed provider information."""
        info = super().get_provider_info()
        info.update({
            'provider_type': 'harvard_bedrock',
            'api_version': self.api_version,
            'base_url': self.base_url,
            'temperature': self.temperature,
            'max_tokens': self.max_tokens,
            'timeout': self.timeout,
            'has_api_key': bool(self.api_key)
        })
        return info
